### ISSUE TITLE
Missing distribution in example

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/inesdata-ml-schema#1]
Everything is empty:
```
distribution:
  - encodingFormat: null
    contentUrl: null
    contentSize: null
    # in this case, quantization does not apply (they can be removed)
    quantizationBits: 
    quantizationMethod: 
```
